// src/validators/bairroValidator.ts (CORRIGIDO)
import { z } from 'zod';

export const bairroSchema = z.object({
  body: z.object({ // <-- Adicionado
    nome_bairro: z.enum([
      'AFOGADOS', 'AGUA_FRIA', 'ALTO_DO_MANDU', 'ALTO_JOSE_BONIFACIO', 'ALTO_JOSE_DO_PINHO', 'APIPUCOS', 'AREIAS', 'ARRUDA', 'BARRO', 'BEBERIBE', 'BOA_VIAGEM', 'BOA_VISTA', 'BOMBA_DO_HEMETERIO', 'BONGI', 'BRASILIA_TEIMOSA', 'BREJO_DA_GUABIRABA', 'BREJO_DE_BEBERIBE', 'CABANGA', 'CACOTE', 'CAJUEIRO', 'CAMPINA_DO_BARRETO', 'CAMPO_GRANDE', 'CASA_AMARELA', 'CASA_FORTE', 'CIDADE_UNIVERSITARIA', 'COELHOS', 'COHAB', 'CORDEIRO', 'CORREGO_DO_JENIPAPO', 'CURADO', 'DERBY', 'DOIS_IRMAOS', 'DOIS_UNIDOS', 'ENCRUZILHADA', 'ENGENHO_DO_MEIO', 'ESPINHEIRO', 'ESTANCIA', 'FUNDAO', 'GRACAS', 'GUABIRABA', 'HIPODROMO', 'IBURA', 'ILHA_DO_LEITE', 'ILHA_DO_RETIRO', 'ILHA_JOANA_BEZERRA', 'IMBIRIBEIRA', 'IPSEP', 'IRAJA', 'JAQUEIRA', 'JARDIM_SAO_PAULO', 'JIQUIA', 'LINHA_DO_TIRO', 'MACAXEIRA', 'MADALENA', 'MANGABEIRA', 'MANGUEIRA', 'MONTEIRO', 'MORRO_DA_CONCEICAO', 'MUSTARDINHA', 'NOVA_DESCOBERTA', 'PAISSANDU', 'PARNAMIRIM', 'PASSARINHO', 'PAU_FERRO', 'PEIXINHOS', 'PINA', 'POCO_DA_PANELA', 'PONTO_DE_PARADA', 'PORTO_DA_MADEIRA', 'PRADO', 'RECIFE_ANTIGO', 'ROSARINHO', 'SANCHO', 'SANTANA', 'SANTO_AMARO', 'SANTO_ANTONIO', 'SAO_JOSE', 'SITIO_DOS_PINTOS', 'SOLEDADE', 'TAMARINEIRA', 'TEJIPIO', 'TORRE', 'TORREAO', 'TORROES', 'TOTO', 'TRES_PONTES', 'VARZEA', 'VASCO_DA_GAMA', 'ZUMBI', 'OUTROS'
    ], {
      required_error: 'O nome do bairro é obrigatório.',
      invalid_type_error: "Bairro inválido. Forneça um dos valores predefinidos."
    }),
    regiao: z.string().optional(),
    ais: z.string().optional(),
  }),
});